POST http://localhost:3003/pizza/create
Content-Type: application/json

{
    "name": "Brigadeiro",
    "price": "38"
}

###
GET http://localhost:3003/pizza/all-pizzas
Content-Type: application/json

###
POST http://localhost:3003/order/create
Content-Type: application/json

{
    "name": "Gabi",
    "id_pizza": "1d884a12-2073-48f6-b5ca-2502f4c11cea",
    "qty_pizza": "3"
}

###
GET http://localhost:3003/order/orders
Content-Type: application/json

###
GET http://localhost:3003/order/orders/908ea935-3e68-4706-b9c8-7d4d4da39db7
Content-Type: application/json